name = "offchain-gateway"
compatibility_date = "2022-06-20"
account_id = "de97cd2a1370a6ed2ad759f894179bff"
main = "./dist/index.js"
node_compat = true
kv_namespaces = [
    { binding = "OFFCHAIN_STORE_DEV", id = "eecc23992fe64d0ebd577896db6a94a4", preview_id = "eecc23992fe64d0ebd577896db6a94a4" }
]

[vars]
OG_DATA = "test.eth.json"
OG_TTL = "60"
